CREATE TABLE Account (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL,
    balance NUMERIC(10, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    version INT NOT NULL DEFAULT 1 
);
